name: update-cls

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */4 * * *"   # Job1 هر ۴ ساعت
    - cron: "0 */6 * * *"   # Job2 هر ۶ ساعت
    - cron: "0 */8 * * *"   # Job3 هر ۸ ساعت

permissions:
  contents: write

jobs:
  cl-job:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - run: pip install requests psutil retrying PyYaml || echo "skip install"
      - run: timeout 180s python cl.py || echo "❌ cl.py failed or skipped"
      - run: |
          for file in normal.txt final.txt; do
            if [ -s "$file" ]; then
              git config user.name github-actions[bot]
              git config user.email 41898282+github-actions[bot]@users.noreply.github.com
              git add "$file"
              git commit -m "auto update from cl.py [skip ci]" || echo "No changes"
              git push || echo "skip push"
            else
              echo "⚠️ $file empty or missing, skipping commit"
            fi
          done

  cl2-job:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - run: pip install requests psutil retrying PyYaml || echo "skip install"
      - run: timeout 300s python cl2.py || echo "❌ cl2.py failed or skipped"
      - run: |
          for file in normal2.txt final2.txt; do
            if [ -s "$file" ]; then
              git config user.name github-actions[bot]
              git config user.email 41898282+github-actions[bot]@users.noreply.github.com
              git add "$file"
              git commit -m "auto update from cl2.py [skip ci]" || echo "No changes"
              git push || echo "skip push"
            else
              echo "⚠️ $file empty or missing, skipping commit"
            fi
          done

  cl3-job:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - run: pip install requests psutil retrying PyYaml || echo "skip install"
      - run: timeout 300s python cl3.py || echo "❌ cl3.py failed or skipped"
      - run: |
          for file in normal.json final.json; do
            if [ -s "$file" ]; then
              git config user.name github-actions[bot]
              git config user.email 41898282+github-actions[bot]@users.noreply.github.com
              git add "$file"
              git commit -m "auto update from cl3.py [skip ci]" || echo "No changes"
              git push || echo "skip push"
            else
              echo "⚠️ $file empty or missing, skipping commit"
            fi
          done
