name: update-cl3

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */8 * * *"   # اجرای cl3.py هر ۸ ساعت

permissions:
  contents: write

jobs:
  cl3-job:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - run: pip install requests psutil retrying PyYaml || echo "skip install"
      - run: timeout 600s python cl3.py || echo "❌ cl3.py failed or skipped"
      - run: |
          if [[ -s normal2.json || -s final2.json ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add normal2.json final2.json
            git commit -m "auto update from cl3.py [skip ci]" || echo "No changes"
            git push || echo "skip push"
          else
            echo "⚠️ normal2.json یا final2.json خالی یا موجود نیست، commit نشد"
          fi
