name: update-cl1560

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */12 * * *"   # اجرای cl1560.py هر 12 ساعت

permissions:
  contents: write

jobs:
  cl-job:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - run: pip install requests psutil retrying PyYaml || echo "skip install"
      - run: timeout 300s python cl1560.py || echo "❌ cl1560.py failed or skipped"
      - run: |
          if [[ -s final1560.txt || -s normal1560.txt ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add final1560.txt normal1560.txt
            git commit -m "auto update from cl1560.py [skip ci]" || echo "No changes"
            git push || echo "skip push"
          else
            echo "⚠️ final1560.txt یا normal1560.txt خالی یا موجود نیست، commit نشد"
